// File generated by FlutterFire CLI (or manually created).
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return android;
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-SXJVc04abodp8zrIUCVMm5MZFgg9zhw',
    appId: '1:785893277995:android:e2edfc91a9e3cbfe9fc56e',
    messagingSenderId: '785893277995',
    projectId: 'photo-shield',
    storageBucket: 'photo-shield.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-SXJVc04abodp8zrIUCVMm5MZFgg9zhw',
    appId: '1:785893277995:ios:PLACEHOLDER',
    messagingSenderId: '785893277995',
    projectId: 'photo-shield',
    storageBucket: 'photo-shield.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-SXJVc04abodp8zrIUCVMm5MZFgg9zhw',
    appId: '1:785893277995:ios:PLACEHOLDER',
    messagingSenderId: '785893277995',
    projectId: 'photo-shield',
    storageBucket: 'photo-shield.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-SXJVc04abodp8zrIUCVMm5MZFgg9zhw',
    appId: '1:785893277995:windows:PLACEHOLDER',
    messagingSenderId: '785893277995',
    projectId: 'photo-shield',
    storageBucket: 'photo-shield.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-SXJVc04abodp8zrIUCVMm5MZFgg9zhw',
    appId: '1:785893277995:web:PLACEHOLDER',
    messagingSenderId: '785893277995',
    projectId: 'photo-shield',
    storageBucket: 'photo-shield.firebasestorage.app',
  );
}
